const FORMS_CONFIG = {
  prescription: {
    name: "Prescription Pad",
    template: "template.png",
    canvasWidth: 3508,
    canvasHeight: 2480,
    pdfOrientation: "l", // 'l' for landscape, 'p' for portrait
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "Left Half",
        fields: [
          {
            id: "name1",
            label: "Name",
            placeholder: "Name",
            type: "text",
            x: 315,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 2
          },
          {
            id: "date1",
            label: "Date",
            placeholder: "Date",
            type: "text",
            class: "small",
            x: 1140,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            showNowButton: true,
            nowButtonMode: "date",
          },
          {
            id: "ward1",
            label: "Ward/Unit",
            placeholder: "Ward/Unit",
            type: "text",
            x: 320,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "age1",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 920,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "tag1",
            label: "Tag #",
            placeholder: "Tag #",
            type: "text",
            class: "small",
            x: 1140,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "text1",
            label: "Prescription",
            placeholder: "Prescription (Left)",
            type: "textarea",
            x: 185,
            y: 800,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1200,
            lineHeight: 36,
            flex: 1,
          },
        ],
      },
      {
        title: "Right half",
        fields: [
          {
            id: "name2",
            label: "Name",
            placeholder: "Name",
            type: "text",
            x: 2069,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 2,
          },
          {
            id: "date2",
            label: "Date",
            placeholder: "Date",
            type: "text",
            class: "small",
            x: 2894,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            showNowButton: true,
            nowButtonMode: "date",
          },
          {
            id: "ward2",
            label: "Ward/Unit",
            placeholder: "Ward/Unit",
            type: "text",
            x: 2074,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "age2",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 2674,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "tag2",
            label: "Tag #",
            placeholder: "Tag #",
            type: "text",
            class: "small",
            x: 2894,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "text2",
            label: "Prescription",
            placeholder: "Prescription (Right)",
            type: "textarea",
            x: 1939,
            y: 800,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1200,
            lineHeight: 36,
            flex: 1,
          },
        ],
      },
    ],
  },
  idrformat: {
    name: "IDR Format 2026",
    template: "idrformat2026.png",
    canvasWidth: 2480, // A4 Portrait 300 DPI
    canvasHeight: 3508,
    pdfOrientation: "p",
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "INTER-DEPARTMENTAL REFERRAL SHEET",
        fields: [
          {
            id: "idr_datetime",
            label: "Date and Time",
            placeholder: "Date and Time Referred:",
            type: "text",
            x: 615,
            y: 770,
            font: "36px 'Iosevka', monospace",
            newRow: true,
            flex: 1,
            showNowButton: true,
            nowButtonMode: "datetime",
          },
          {
            id: "idr_agesex",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 1580,
            y: 770,
            font: "36px 'Iosevka', monospace",
            flex: 1
          },
          {
            id: "idr_referred_from",
            label: "Referred From (Department)",
            placeholder: "Referred From (Department):",
            type: "text",
            x: 615,
            y: 855,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "idr_referring_physician",
            label: "Referring Physician",
            placeholder: "Referring Physician:",
            type: "text",
            x: 615,
            y: 955,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "idr_referred_to",
            label: "Referred To",
            placeholder: "Referred to (Department):",
            type: "text",
            x: 615,
            y: 1055,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "idr_reason_for_referral",
            label: "Reason for Referral",
            placeholder: "Reason for referral:",
            type: "textarea",
            x: 160,
            y: 1180,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 36,
          },
          {
            id: "idr_pertinent_history_pe",
            label: "Pertinent History and PE",
            placeholder: "Pertinent history and PE:",
            type: "textarea",
            x: 160,
            y: 1490,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 36,
          },
          {
            id: "idr_assessment",
            label: "Assessment",
            placeholder: "Assessment:",
            type: "textarea",
            x: 160,
            y: 2650,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 36,
          },
          {
            id: "idr_name",
            label: "Patient Name",
            placeholder: "Patient Name:",
            type: "text",
            x: 160,
            y: 3175,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "idr_hospital_no",
            label: "Hospital no",
            placeholder: "Hospital No:",
            type: "text",
            x: 1600,
            y: 3175,
            font: "36px 'Iosevka', monospace",
          },
        ],
      },
    ],
  },
  orproposal: {
    name: "OR Proposal",
    template: "orproposal.png",
    canvasWidth: 2480, // A4 Portrait 300 DPI
    canvasHeight: 3508,
    pdfOrientation: "p",
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "OR Proposal",
        fields: [
          {
            id: "orp_department",
            label: "department",
            placeholder: "Department of: ",
            type: "text",
            x: 660,
            y: 730,
            font: "36px 'Iosevka', monospace",
            flex: 4
          },
          {
            id: "orp_date",
            label: "date",
            placeholder: "Date:",
            type: "text",
            class: "small",
            x: 1720,
            y: 730,
            font: "36px 'Iosevka', monospace",
            flex: 2,
            showNowButton: true,
            nowButtonMode: "date",
          },
          {
            id: "orp_name",
            label: "Name of Patient",
            placeholder: "Name of Patient:",
            type: "text",
            x: 680,
            y: 810,
            font: "36px 'Iosevka', monospace",
            newRow: true,
            flex: 4
          },
          {
            id: "orp_age",
            label: "age of Patient",
            placeholder: "Age:",
            type: "text",
            x: 1720,
            y: 810,
            font: "36px 'Iosevka', monospace",
            flex: 1
          },
          {
            id: "orp_sex",
            label: "Sex of Patient",
            placeholder: "Sex:",
            type: "text",
            x: 1940,
            y: 810,
            font: "36px 'Iosevka', monospace",
            flex: 1
          },
          {
            id: "orp_floor_bed",
            label: "Floor and Bed Number",
            placeholder: "Floor and Bed Number:",
            type: "text",
            x: 700,
            y: 895,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_impression",
            label: "impression",
            placeholder: "Impression:",
            type: "text",
            x: 560,
            y: 980,
            font: "28px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1800,
            lineHeight: 28,
            anchorBottom: true,
            newRow: true
          },
          {
            id: "orp_proposed_operation",
            label: "Proposed Operation",
            placeholder: "Proposed operation:",
            type: "text",
            x: 770,
            y: 1060,
            font: "28px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1600,
            lineHeight: 28,
            anchorBottom: true,
            newRow: true
          },
          {
            id: "orp_date_and_time",
            label: "Date and Time of Surgery",
            placeholder: "Date and Time of Surgery:",
            type: "text",
            x: 620,
            y: 1130,
            font: "36px 'Iosevka', monospace",
            newRow: true,
          },
          {
            id: "orp_est_time_surgery",
            label: "Estimated Time of Surgery",
            placeholder: "Estimated Time of Surgery:",
            type: "text",
            x: 910,
            y: 1210,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_surgeon",
            label: "Surgeon Name",
            placeholder: "Surgeon:",
            type: "text",
            x: 520,
            y: 1290,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_asstsurgeon",
            label: "Asst Surgeon Name",
            placeholder: "Asst Surgeon:",
            type: "text",
            x: 1500,
            y: 1290,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "orp_anesthesiologist",
            label: "Anesthesiologist Name",
            placeholder: "Anesthesiologist:",
            type: "text",
            x: 710,
            y: 1370,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_position_during_surgery",
            label: "Position During Surgery",
            placeholder: "Position during Surgery:",
            type: "text",
            x: 870,
            y: 1450,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_instruments",
            label: "Instruments needed",
            placeholder: "Instruments needed:",
            type: "text",
            x: 770,
            y: 1540,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_dept_head",
            label: "Department Head",
            placeholder: "Department Head:",
            type: "text",
            x: 300,
            y: 1950,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_or_manager",
            label: "OR Manager",
            placeholder: "OR Manager:",
            type: "text",
            x: 1520,
            y: 1950,
            font: "36px 'Iosevka', monospace"
          },
        ],
      },
    ],
  },
  orproposal_batch: {
    name: "Batch OR Proposal Generator (BETA)",
    template: "orproposal.png",
    canvasWidth: 2480,
    canvasHeight: 3508,
    pdfOrientation: "p",
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: []
  },
  radio: {
    name: "Radio Request",
    template: "radiorequest.png",
    canvasWidth: 2550,
    canvasHeight: 3300,
    pdfOrientation: "p", // 'l' for landscape, 'p' for portrait
    pdfUnit: "pt",
    pdfFormat: "letter",
    sections: [
      {
        title: "Top half",
        fields: [
          {
            id: "hosp-no1",
            label: "Hospital #",
            placeholder: "Hospital #",
            type: "text",
            x: 435,
            y: 345 ,
            font: "28px 'Iosevka', monospace",
            anchorBottom: true
          },
          {
            id: "req-no1",
            label: "Requisition No.",
            placeholder: "Requisition No.",
            type: "text",
            x: 1970,
            y: 165,
            font: "28px 'Iosevka', monospace",
            flex: 2,

          },
          {
            id: "date1",
            label: "Date",
            placeholder: "Date",
            type: "text",
            x: 335,
            y: 400,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            showNowButton: true,
            nowButtonMode: "date",
          },
          {
            id: "name1",
            label: "Patient Name",
            placeholder: "Patient Name",
            type: "text",
            x: 500,
            y: 490,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "age1",
            label: "Age",
            placeholder: "Age",
            type: "text",
            x: 310,
            y: 600,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "DOB1",
            label: "Date of Birth",
            placeholder: "Date of Birth",
            type: "text",
            x: 820,
            y: 600,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "ward1",
            label: "Ward",
            placeholder: "Ward",
            type: "text",
            x: 1330,
            y: 600,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "sex1",
            label: "Sex",
            placeholder: "Sex",
            type: "text",
            x: 310,
            y: 650,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "LMP1",
            label: "LMP",
            placeholder: "LMP",
            type: "text",
            x: 660,
            y: 650,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "address1",
            label: "Address",
            placeholder: "Address",
            type: "text",
            x: 380,
            y: 700,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "req_exam1",
            label: "Requested Examination/s",
            placeholder: "Requested Examination/s",
            type: "text",
            x: 680,
            y: 760,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "diag1",
            label: "Diagnosis",
            placeholder: "Diagnosis",
            type: "text",
            x: 405,
            y: 920,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "indication1",
            label: "Indication",
            placeholder: "Indication",
            type: "text",
            x: 950,
            y: 970,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "history1",
            label: "Brief History",
            placeholder: "Brief History",
            type: "textarea",
            x: 225,
            y: 1020,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1600,
            lineHeight: 36,
            flex: 1,
            padSpaces: 13,
            newRow: true
          },
        ],
      },
      {
        title: "Bottom Half",
        fields: [
          {
            id: "hosp-no2",
            label: "Hospital #",
            placeholder: "Hospital #",
            type: "text",
            x: 435,
            y: 1980 ,
            font: "28px 'Iosevka', monospace",
          },
          {
            id: "req-no2",
            label: "Requisition No.",
            placeholder: "Requisition No.",
            type: "text",
            x: 1970,
            y: 1800,
            font: "28px 'Iosevka', monospace",
            flex: 2,

          },
          {
            id: "date2",
            label: "Date",
            placeholder: "Date",
            type: "text",
            x: 335,
            y: 2015,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            showNowButton: true,
            nowButtonMode: "date",
          },
          {
            id: "name2",
            label: "Patient Name",
            placeholder: "Patient Name",
            type: "text",
            x: 500,
            y: 2125,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "age2",
            label: "Age",
            placeholder: "Age",
            type: "text",
            x: 310,
            y: 2225,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "DOB2",
            label: "Date of Birth",
            placeholder: "Date of Birth",
            type: "text",
            x: 820,
            y: 2225,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "ward2",
            label: "Ward",
            placeholder: "Ward",
            type: "text",
            x: 1330,
            y: 2225,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "sex2",
            label: "Sex",
            placeholder: "Sex",
            type: "text",
            x: 310,
            y: 2280,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "LMP2",
            label: "LMP",
            placeholder: "LMP",
            type: "text",
            x: 660,
            y: 2280,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "address2",
            label: "Address",
            placeholder: "Address",
            type: "text",
            x: 380,
            y: 2335,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "req_exam2",
            label: "Requested Examination/s",
            placeholder: "Requested Examination/s",
            type: "text",
            x: 680,
            y: 2385,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "diag2",
            label: "Diagnosis",
            placeholder: "Diagnosis",
            type: "text",
            x: 405,
            y: 2545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "indication2",
            label: "Indication",
            placeholder: "Indication",
            type: "text",
            x: 950,
            y: 2600,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "history2",
            label: "Brief History",
            placeholder: "Brief History",
            type: "textarea",
            x: 225,
            y: 2645,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1600,
            lineHeight: 36,
            flex: 1,
            padSpaces: 13,
            newRow: true
          },
        ],
      },
    ],
  },
  radio_combined: {
    name: "Radio Combined (Request + CT Scan)",
    canvasWidth: 2480,
    canvasHeight: 3508,
    pdfOrientation: "p", // 'l' for landscape, 'p' for portrait
    pdfUnit: "pt",
    pdfFormat: "a4",
    // Shared UI fields (rendered once in the form). Coordinates here are for
    // the live preview (page 1). Each page in `pages` has its own coordinates.
    sections: [
      {
        title: "Radio Combined",
        fields: [
          {
            id: "hosp-no1",
            label: "Hospital #",
            placeholder: "Hospital #",
            type: "text",
            font: "28px 'Iosevka', monospace",
            anchorBottom: true
          },
          {
            id: "req-no1",
            label: "Requisition No.",
            placeholder: "Requisition No.",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 2,
          },
          {
            id: "date1",
            label: "Date",
            placeholder: "Date",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            showNowButton: true,
            nowButtonMode: "date",
          },
          {
            id: "name1",
            label: "Patient Name",
            placeholder: "Patient Name",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "age1",
            label: "Age",
            placeholder: "Age",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "DOB1",
            label: "Date of Birth",
            placeholder: "Date of Birth",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "ward1",
            label: "Ward",
            placeholder: "Ward",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "sex1",
            label: "Sex",
            placeholder: "Sex",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "LMP1",
            label: "LMP",
            placeholder: "LMP",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "address1",
            label: "Address",
            placeholder: "Address",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "req_exam1",
            label: "Requested Examination/s",
            placeholder: "Requested Examination/s",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "diag1",
            label: "Diagnosis",
            placeholder: "Diagnosis",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "indication1",
            label: "Indication",
            placeholder: "Indication",
            type: "text",
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "history1",
            label: "Brief History",
            placeholder: "Brief History",
            type: "textarea",
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1200,
            lineHeight: 36,
            flex: 1,
            newRow: true
          },
        ],
      },
    ],
    // Each page has its own template image and per-page field coordinates.
    // The field IDs must match the shared `sections` field IDs above.
    pages: [
      {
        template: "radiorequest.png",
        fields: [
          { id: "hosp-no1", x: 435, y: 365, font: "28px 'Iosevka', monospace", anchorBottom: true },
          { id: "req-no1", x: 1920, y: 185, font: "28px 'Iosevka', monospace" },
          { id: "date1", x: 335, y: 420, font: "28px 'Iosevka', monospace" },
          { id: "name1", x: 500, y: 520, font: "28px 'Iosevka', monospace" },
          { id: "age1", x: 310, y: 640, font: "28px 'Iosevka', monospace" },
          { id: "DOB1", x: 820, y: 640, font: "28px 'Iosevka', monospace" },
          { id: "ward1", x: 1330, y: 640, font: "28px 'Iosevka', monospace" },
          { id: "sex1", x: 310, y: 690, font: "28px 'Iosevka', monospace" },
          { id: "LMP1", x: 660, y: 690, font: "28px 'Iosevka', monospace" },
          { id: "address1", x: 380, y: 740, font: "28px 'Iosevka', monospace" },
          { id: "req_exam1", x: 680, y: 800, font: "28px 'Iosevka', monospace" },
          { id: "diag1", x: 405, y: 970, font: "28px 'Iosevka', monospace" },
          { id: "indication1", x: 930, y: 1030, font: "28px 'Iosevka', monospace" },
          { id: "history1", x: 225, y: 1090, font: "36px 'Iosevka', monospace", isMultiline: true, maxWidth: 1600, lineHeight: 36, padSpaces: 13 },
        ],
      },
      {
        template: "radioctscana4.png",
        fields: [
          { id: "hosp-no1", x: 1555, y: 550, font: "28px 'Iosevka', monospace", anchorBottom: true },
          { id: "date1", x: 210, y: 550, font: "28px 'Iosevka', monospace" },
          { id: "ward1", x: 2060, y: 550, font: "28px 'Iosevka', monospace" },
          { id: "name1", x: 250, y: 650, font: "28px 'Iosevka', monospace" },
          { id: "age1", x: 1520, y: 650, font: "28px 'Iosevka', monospace" },
          { id: "sex1", x: 1600, y: 650, font: "28px 'Iosevka', monospace" },
          { id: "DOB1", x: 2040, y: 650, font: "28px 'Iosevka', monospace" },
          { id: "address1", x: 260, y: 780, font: "28px 'Iosevka', monospace" },
          { id: "history1", x: 90, y: 1220, font: "36px 'Iosevka', monospace", isMultiline: true, maxWidth: 2300, lineHeight: 36 },
        ],
      },
    ],
  },
  surgpath: {
    name: "Surgical Pathology Form",
    template: "surgpath.png",
    canvasWidth: 2550, // A4 Portrait 300 DPI
    canvasHeight: 3900,
    pdfOrientation: "p",
    pdfUnit: "pt",
    pdfFormat: "legal",
    sections: [
      {
        title: "Surgical Pathology Form",
        fields: [
          {
            id: "sp_name", label: "Name", placeholder: "Name:",
            type: "text", class: "small", x: 240, y: 490,
            font: "36px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "sp_age", label: "Age", placeholder: "Age:",
            type: "text", class: "small", x: 240, y: 620,
            font: "36px 'Iosevka', monospace",
            flex: 1
          },
          {
            id: "sp_civil_status", label: "Civil Status", placeholder: "Civil Status:",
            type: "text", x: 750, y: 620,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "sp_address", label: "Address", placeholder: "Address:",
            type: "text", x: 1040, y: 620,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "sp_ward", label: "Ward:", placeholder: "Ward:",
            type: "text", x: 240, y: 740,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "sp_bed", label: "Bed:", placeholder: "Bed:",
            type: "text", x: 750, y: 740,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "sp_contact_no", label: "Contact No:", placeholder: "Contact No:",
            type: "text", x: 1030, y: 740,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "sp_datetime", label: "Date and Time", placeholder: "Date and Time Referred:",
            type: "text", x: 1740, y: 740,
            font: "36px 'Iosevka', monospace",
            showNowButton: true,
            nowButtonMode: "datetime",
          },
          {
            id: "sp_source", label: "Source of Specimen:", placeholder: "Source of Specimen:",
            type: "text", x: 240, y: 860,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "sp_history_pe", label: "Pertinent History and PE", placeholder: "Pertinent history and PE:",
            type: "textarea", x: 150, y: 1090,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1150,
            lineHeight: 36,
            newRow: true
          },
          {
            id: "sp_imaging", label: "Imaging", placeholder: "Imaging:",
            type: "textarea", x: 1340, y: 1120,
            font: "36px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1050,
            lineHeight: 36,
            newRow: true
          },
          {
            id: "sp_pmh", label: "Pertinent Past Medical History:", placeholder: "Pertinent Past Medical History:",
            type: "text", x: 135, y: 1840,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "sp_treatment", label: "Prior and Current Treatment:", placeholder: "Prior and Current Treatment:",
            type: "text", x: 1360, y: 1840,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "sp_operationdone", label: "Operation Done", placeholder: "Operation Done:",
            type: "text", x: 135, y: 2130,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "sp_timeofremoval", label: "Time of Removal", placeholder: "Time of Removal:",
            type: "text", x: 1360, y: 2010,
            font: "36px 'Iosevka', monospace",
          },
          {
            id: "sp_suturetags", label: "Suture Tags", placeholder: "Suture Tags:",
            type: "text", x: 615, y: 955,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "sp_postopdiag", label: "Post Operative Diagnosis", placeholder: "Post Operative Diagnosis:",
            type: "text", x: 135, y: 2250,
            font: "36px 'Iosevka', monospace",
            newRow: true
          },
        ],
      },
    ],
  },
};
  