const FORMS_CONFIG = {
  prescription: {
    name: "Prescription Pad",
    template: "template.png",
    canvasWidth: 3508,
    canvasHeight: 2480,
    pdfOrientation: "l", // 'l' for landscape, 'p' for portrait
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "Left Half",
        fields: [
          {
            id: "name1",
            label: "Name",
            placeholder: "Name",
            type: "text",
            x: 315,
            y: 445,
            font: "28px 'RobotoMono', monospace",
            flex: 3,
          },
          {
            id: "date1",
            label: "Date",
            placeholder: "Date",
            type: "text",
            class: "small",
            x: 1140,
            y: 445,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "ward1",
            label: "Ward/Unit",
            placeholder: "Ward/Unit",
            type: "text",
            x: 320,
            y: 545,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "age1",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 920,
            y: 545,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "tag1",
            label: "Tag #",
            placeholder: "Tag #",
            type: "text",
            class: "small",
            x: 1140,
            y: 545,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "text1",
            label: "Prescription",
            placeholder: "Prescription (Left)",
            type: "textarea",
            x: 185,
            y: 825,
            font: "34px 'RobotoMono', monospace",
            isMultiline: true,
            lineHeight: 65,
            flex: 1,
          },
        ],
      },
      {
        title: "Right half",
        fields: [
          {
            id: "name2",
            label: "Name",
            placeholder: "Name",
            type: "text",
            x: 2069,
            y: 445,
            font: "28px 'RobotoMono', monospace",
            flex: 3,
          },
          {
            id: "date2",
            label: "Date",
            placeholder: "Date",
            type: "text",
            class: "small",
            x: 2894,
            y: 445,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "ward2",
            label: "Ward/Unit",
            placeholder: "Ward/Unit",
            type: "text",
            x: 2074,
            y: 545,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "age2",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 2674,
            y: 545,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "tag2",
            label: "Tag #",
            placeholder: "Tag #",
            type: "text",
            class: "small",
            x: 2894,
            y: 545,
            font: "28px 'RobotoMono', monospace",
            flex: 1,
          },
          {
            id: "text2",
            label: "Prescription",
            placeholder: "Prescription (Right)",
            type: "textarea",
            x: 1939,
            y: 825,
            font: "34px 'RobotoMono', monospace",
            isMultiline: true,
            lineHeight: 65,
            flex: 1,
          },
        ],
      },
    ],
  },
  idrformat: {
    name: "IDR Format 2026",
    template: "idrformat2026.png",
    canvasWidth: 2480, // A4 Portrait 300 DPI
    canvasHeight: 3508,
    pdfOrientation: "p",
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "Patient Information",
        fields: [
          {
            id: "idr_datetime",
            label: "Date and Time",
            placeholder: "Date and Time Referred",
            type: "text",
            x: 615,
            y: 770,
            font: "48px 'RobotoMono', monospace",
          },
          {
            id: "idr_agesex",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 1580,
            y: 770,
            font: "48px 'RobotoMono', monospace",
          },
          {
            id: "idr_referred_from",
            label: "Referred From",
            placeholder: "Referred From",
            type: "text",
            x: 615,
            y: 855,
            font: "48px 'RobotoMono', monospace",
          },
          {
            id: "idr_referring_physician",
            label: "Referring Physician",
            placeholder: "Enter Referring Physician",
            type: "text",
            x: 615,
            y: 955,
            font: "48px 'RobotoMono', monospace",
          },
          {
            id: "idr_referred_to",
            label: "Referred To",
            placeholder: "Enter Referred to Department",
            type: "text",
            x: 615,
            y: 1055,
            font: "48px 'RobotoMono', monospace",
          },
          {
            id: "idr_reason_for_referral",
            label: "Reason for Referral",
            placeholder: "Enter reason for referral...",
            type: "textarea",
            x: 160,
            y: 1180,
            font: "48px 'RobotoMono', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 60,
          },
          {
            id: "idr_pertinent_history_pe",
            label: "Pertinent History and PE",
            placeholder: "Enter pertinent history and PE...",
            type: "textarea",
            x: 160,
            y: 1490,
            font: "48px 'RobotoMono', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 60,
          },
          {
            id: "idr_assessment",
            label: "Assessment",
            placeholder: "Enter assessment...",
            type: "textarea",
            x: 160,
            y: 2650,
            font: "48px 'RobotoMono', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 60,
          },
          {
            id: "idr_name",
            label: "Patient Name",
            placeholder: "Enter Patient name",
            type: "text",
            x: 160,
            y: 3175,
            font: "48px 'RobotoMono', monospace",
          },
          {
            id: "idr_hospital_no",
            label: "Hospital no",
            placeholder: "Enter hospital no",
            type: "text",
            x: 1600,
            y: 3175,
            font: "48px 'RobotoMono', monospace",
          },
        ],
      },
    ],
  },
};
