const FORMS_CONFIG = {
  prescription: {
    name: "Prescription Pad",
    template: "template.png",
    canvasWidth: 3508,
    canvasHeight: 2480,
    pdfOrientation: "l", // 'l' for landscape, 'p' for portrait
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "Left Half",
        fields: [
          {
            id: "name1",
            label: "Name",
            placeholder: "Name",
            type: "text",
            x: 315,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 2 
          },
          {
            id: "date1",
            label: "Date",
            placeholder: "Date",
            type: "text",
            class: "small",
            x: 1140,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            showNowButton: true,
          },
          {
            id: "ward1",
            label: "Ward/Unit",
            placeholder: "Ward/Unit",
            type: "text",
            x: 320,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "age1",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 920,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "tag1",
            label: "Tag #",
            placeholder: "Tag #",
            type: "text",
            class: "small",
            x: 1140,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "text1",
            label: "Prescription",
            placeholder: "Prescription (Left)",
            type: "textarea",
            x: 185,
            y: 825,
            font: "34px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1200,
            lineHeight: 65,
            flex: 1,
          },
        ],
      },
      {
        title: "Right half",
        fields: [
          {
            id: "name2",
            label: "Name",
            placeholder: "Name",
            type: "text",
            x: 2069,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 2,
          },
          {
            id: "date2",
            label: "Date",
            placeholder: "Date",
            type: "text",
            class: "small",
            x: 2894,
            y: 445,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            showNowButton: true,
          },
          {
            id: "ward2",
            label: "Ward/Unit",
            placeholder: "Ward/Unit",
            type: "text",
            x: 2074,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
            newRow: true
          },
          {
            id: "age2",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 2674,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "tag2",
            label: "Tag #",
            placeholder: "Tag #",
            type: "text",
            class: "small",
            x: 2894,
            y: 545,
            font: "28px 'Iosevka', monospace",
            flex: 1,
          },
          {
            id: "text2",
            label: "Prescription",
            placeholder: "Prescription (Right)",
            type: "textarea",
            x: 1939,
            y: 825,
            font: "34px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 1200,
            lineHeight: 65,
            flex: 1,
          },
        ],
      },
    ],
  },
  idrformat: {
    name: "IDR Format 2026",
    template: "idrformat2026.png",
    canvasWidth: 2480, // A4 Portrait 300 DPI
    canvasHeight: 3508,
    pdfOrientation: "p",
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "INTER-DEPARTMENTAL REFERRAL SHEET",
        fields: [
          {
            id: "idr_datetime",
            label: "Date and Time",
            placeholder: "Date and Time Referred:",
            type: "text",
            x: 615,
            y: 770,
            font: "48px 'Iosevka', monospace",
            newRow: true,
            flex: 1,
            showNowButton: true,
          },
          {
            id: "idr_agesex",
            label: "Age/Sex",
            placeholder: "Age/Sex",
            type: "text",
            class: "small",
            x: 1580,
            y: 770,
            font: "48px 'Iosevka', monospace",
            flex: 1
          },
          {
            id: "idr_referred_from",
            label: "Referred From (Department)",
            placeholder: "Referred From (Department):",
            type: "text",
            x: 615,
            y: 855,
            font: "48px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "idr_referring_physician",
            label: "Referring Physician",
            placeholder: "Referring Physician:",
            type: "text",
            x: 615,
            y: 955,
            font: "48px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "idr_referred_to",
            label: "Referred To",
            placeholder: "Referred to (Department):",
            type: "text",
            x: 615,
            y: 1055,
            font: "48px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "idr_reason_for_referral",
            label: "Reason for Referral",
            placeholder: "Reason for referral:",
            type: "textarea",
            x: 160,
            y: 1180,
            font: "48px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 60,
          },
          {
            id: "idr_pertinent_history_pe",
            label: "Pertinent History and PE",
            placeholder: "Pertinent history and PE:",
            type: "textarea",
            x: 160,
            y: 1490,
            font: "48px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 60,
          },
          {
            id: "idr_assessment",
            label: "Assessment",
            placeholder: "Assessment:",
            type: "textarea",
            x: 160,
            y: 2650,
            font: "48px 'Iosevka', monospace",
            isMultiline: true,
            maxWidth: 2200,
            lineHeight: 60,
          },
          {
            id: "idr_name",
            label: "Patient Name",
            placeholder: "Patient Name:",
            type: "text",
            x: 160,
            y: 3175,
            font: "48px 'Iosevka', monospace",
          },
          {
            id: "idr_hospital_no",
            label: "Hospital no",
            placeholder: "Hospital No:",
            type: "text",
            x: 1600,
            y: 3175,
            font: "48px 'Iosevka', monospace",
          },
        ],
      },
    ],
  },
  orproposal: {
    name: "OR Proposal",
    template: "orproposal.png",
    canvasWidth: 2480, // A4 Portrait 300 DPI
    canvasHeight: 3508,
    pdfOrientation: "p",
    pdfUnit: "pt",
    pdfFormat: "a4",
    sections: [
      {
        title: "OR Proposal",
        fields: [
          {
            id: "orp_department",
            label: "department",
            placeholder: "Department Of: ",
            type: "text",
            x: 660,
            y: 720,
            font: "28px 'Iosevka', monospace",
            flex: 4
          },
          {
            id: "orp_date",
            label: "date",
            placeholder: "Date:",
            type: "text",
            class: "small",
            x: 1720,
            y: 720,
            font: "28px 'Iosevka', monospace",
            flex: 2,
            showNowButton: true,
          },
          {
            id: "orp_name",
            label: "Name of Patient",
            placeholder: "Name of Patient:",
            type: "text",
            x: 680,
            y: 800,
            font: "28px 'Iosevka', monospace",
            newRow: true,
            flex: 4
          },
          {
            id: "orp_age",
            label: "age of Patient",
            placeholder: "Age:",
            type: "text",
            x: 1720,
            y: 800,
            font: "28px 'Iosevka', monospace",
            flex: 1
          },
          {
            id: "orp_sex",
            label: "Sex of Patient",
            placeholder: "Sex:",
            type: "text",
            x: 1940,
            y: 800,
            font: "28px 'Iosevka', monospace",
            flex: 1
          },
          {
            id: "orp_floor_bed",
            label: "Floor and Bed Number",
            placeholder: "Floor and Bed Number:",
            type: "text",
            x: 700,
            y: 890,
            font: "28px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_impression",
            label: "impression",
            placeholder: "Impression:",
            type: "text",
            x: 560,
            y: 975,
            font: "26px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_proposed_operation",
            label: "Proposed Operation",
            placeholder: "Proposed operation:",
            type: "text",
            x: 770,
            y: 1050,
            font: "26px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_date_and_time",
            label: "Date and Time of Surgery",
            placeholder: "Date and Time of Surgery:",
            type: "text",
            x: 620,
            y: 1130,
            font: "28px 'Iosevka', monospace",
            newRow: true,
          },
          {
            id: "orp_est_time_surgery",
            label: "Estimated Time of Surgery",
            placeholder: "Estimated Time of Surgery:",
            type: "text",
            x: 910,
            y: 1210,
            font: "28px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_surgeon",
            label: "Surgeon Name",
            placeholder: "Surgeon:",
            type: "text",
            x: 520,
            y: 1290,
            font: "28px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_asstsurgeon",
            label: "Asst Surgeon Name",
            placeholder: "Asst Surgeon:",
            type: "text",
            x: 1500,
            y: 1290,
            font: "28px 'Iosevka', monospace",
          },
          {
            id: "orp_anesthesiologist",
            label: "Anesthesiologist Name",
            placeholder: "Anesthesiologist:",
            type: "text",
            x: 710,
            y: 1370,
            font: "28px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_position_during_surgery",
            label: "Position During Surgery",
            placeholder: "Position during Surgery:",
            type: "text",
            x: 870,
            y: 1450,
            font: "28px 'Iosevka', monospace",
            newRow: true
          },
          {
            id: "orp_instruments",
            label: "Instruments needed",
            placeholder: "Instruments needed:",
            type: "text",
            x: 770,
            y: 1540,
            font: "28px 'Iosevka', monospace",
            newRow: true
          },
        ],
      },
    ],
  },
};
